baseURL: https://esa.harutiro.net/
languageCode: ja
title: sysken site
publishDir: "docs"

module:
  # uncomment line below for temporary local development of module
  # replacements: "github.com/CaiJimmy/hugo-theme-stack/v3 -> ../../hugo-theme-stack"
  imports:
    - path: github.com/CaiJimmy/hugo-theme-stack/v3
      disable: false



params:
    custom_css: ["css/custom.css"]
    mainSections:
        - post
    featuredImageField: image
    rssFullContent: true
    favicon: /img/favicon.ico

    footer:
      since: 2022

    sidebar:
        # emoji: 🍥
        subtitle: しすけんテストウェブ
        avatar:
            enabled: true
            local: false
            src: /img/set_icon_400x400.jpg

    opengraph:
        twitter:
            # Your Twitter username
            site:

            # Available values: summary, summary_large_image
            card: summary_large_image

    widgets:
        enabled:
            - search
            - archives
            - tag-cloud

        archives:
            limit: 5

        tagCloud:
            limit: 10

menu:
    main:
      - identifier: home
        name: Home
        url: /
        params:
          icon: home

      - identifier: about
        name: About
        url: /about
        params:
          icon: user

      - identifier: app
        name: App
        url: /app
        params:
          icon: tag

      - identifier: archives
        name: Archives
        url: /archives
        params:
          icon: archives

      - identifier: search
        name: Search
        url: /search/search_index/
        params:
          icon: search

    social:
        - identifier: github
          name: GitHub
          url: https://github.com/SystemEngineeringTeam
          params:
              icon: brand-github

        - identifier: twitter
          name: Twitter
          url: https://twitter.com/set_official
          params:
              icon: brand-twitter
        
        - identifier: qiita
          name: Qiita
          url: https://qiita.com/organizations/sysken
          params:
              icon: qiita